### ISSUE TITLE
Extend LPP

### ISSUE THREAD

**Issue by j-forster** [Waziup/WaziGate#121]
LPP is used by Wazigate through ChirpStack as payload encoding for LoRaWAN sensors.
The binary payload is very slim and fits very well for low-memory devices like the Wazidev.

See https://community.mydevices.com/t/cayenne-lpp-2-0/7510 for the somehow unfinished v2.0 spec ideas.

The spec covers the following sensors types:

Type | IPSO | LPP | Hex | Data Size | Data Resolution per bit
-- | -- | -- | -- | -- | --
Digital Input | 3200 | 0 | 0 | 1 | 1
Digital Output | 3201 | 1 | 1 | 1 | 1
Analog Input | 3202 | 2 | 2 | 2 | 0.01 Signed
Analog Output | 3203 | 3 | 3 | 2 | 0.01 Signed
Illuminance Sensor | 3301 | 101 | 65 | 2 | 1 Lux Unsigned MSB
Presence Sensor | 3302 | 102 | 66 | 1 | 1
Temperature Sensor | 3303 | 103 | 67 | 2 | 0.1 °C Signed MSB
Humidity Sensor | 3304 | 104 | 68 | 1 | 0.5 % Unsigned
Accelerometer | 3313 | 113 | 71 | 6 | 0.001 G Signed MSB per axis
Barometer | 3315 | 115 | 73 | 2 | 0.1 hPa Unsigned MSB
Gyrometer | 3334 | 134 | 86 | 6 | 0.01 °/s Signed MSB per axis
GPS Location | 3336 | 136 | 88 | 9 | Latitude : 0.0001 ° Signed MSB Longitude : 0.0001 ° Signed MSB Altitude : 0.01 meter Signed MSB

Actuation is limited to analog values (2 Byte, 0.01 Signed) covering digital values as analog value (HIGH = 100 = 0x0064).

# LPP with Waziup

Waziup has a wider range of sensor and actuator types, and (as a test and development platform) should be able to transmit arbitrary generic data (like JSON).

For existing Wazidevs, a new protocol should extend (not replace) the LPP format for downwards compatibility.

A possible candidate for a extension protocol is BSON for payload encoding, but BSON is not very optimized for low-low-memory environments (e.g. BSON strings are prefixed with a int32 length which outranges the ~250B LoRaWAN message limit completely; thus string sizes could be limited to int8 length).
The new payload encoding should cover basic plain C values (int8, int16, float32, bool, ...), strings (with 1B length prefix), variant ints, simple arrays, and maybe simple objects (key/value).

This issue should track the discussion and implementation details of such a payload encoding for Wazigate.

# Tasks

- [ ] Extend Waziup LPP Spec
- [ ] Implement Go Decoder/Encoder (for Wazigate)
- [ ] Implement C Reader/Writer for Wazidev

**Comment by cdupont** [comment]
Just a question: "Actuation is limited to analog values (2 Byte, 0.01 Signed) covering digital values as analog value (HIGH = 100 = 0x0064)."
Why not using digital values instead of analog values? Why HIGH=100 and not 1?

**Comment by j-forster** [comment]
Taken from [4.5. Actuator Commands]( https://community.mydevices.com/t/cayenne-lpp-2-0/7510/28909):

> As the actuator is basically a digital one (on/off, low/high), or an analog one (any value); and since the device developer is responsible of the channel mapping; data format is shared for both digital and analog actuators commands, removing the type byte.
> 
> The drawback is that digital HIGH is sent as a 1.0 analog value within a 2 bytes signed integer with 0.01 precision, eg. HIGH = 100 = 0x0064.

It's a 1-byte trade off...
The set of actuators is reduced to a single digital or analog value (2 bytes), but we save one byte per value (leaving out the type byte)

**Comment by cdupont** [comment]
Oh, I see, they use the value 1.0 in their own analog encoding, so 1.0 is encoded as 0x0064.
Regarding removing the type byte, well that does not seem a huge win. Currently it seems to be still there: https://github.com/myDevicesIoT/CayenneLPP/blob/master/src/CayenneLPP.cpp#L74

**Comment by cdupont** [comment]
It would be interesting if we include also an uplink payload for actuators.
The idea is that the device will "declare" an actuator (without any value, or a default current value).
This will allow the gateway to create that device and create it on the Cloud too, just like for Sensors.
So no actions will be required by the user on the 2 dashboards (after entering the LoRaWAN codes).

**Comment by cdupont** [comment]
We also need an acknowledge mechanism for actuation: "actuation taken into account/executed/rejected/not supported"...
The same uplink payload could be used?

**Comment by cdupont** [comment]
I suggest to close this issue since it as been realized.
